// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace AssemblyCSharp
{
	public class PlayerInformation
	{ 
		public int id;
		public string name;
		public string team;
		public int speed;
		public int skill;
		public int power;
		public int level;
		public int jersey;
		public string card;
		public string dunk;
		public int mojo;
	}
}

