// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace WSBB
{
	public class BallerEvents
	{
		public delegate void StatChangeEventHandler(Team team);
		public delegate void StatChangeEventWithBoolHandler(Team team, bool hasPrimary);
		public delegate void DebugTextPrintHandler();
		public delegate void BallPossessionHandler();
		public delegate void BallerTeamActionHandler(Team team);
		public delegate void BallerActionHandler(BBaller bballer);

		public static event StatChangeEventHandler onDerivedStatChange;
		public static event StatChangeEventHandler onPrimaryStatChange;
		public static event StatChangeEventWithBoolHandler onDemandCardStatRecalculation;
		public static event DebugTextPrintHandler onDemandDebugTextUpdate;
		public static event BallPossessionHandler onBallPossessionUpdate;
		public static event BallerTeamActionHandler onDunkCompletionWithMojo;
		public static event BallerTeamActionHandler onDunkCompletion;
		public static event BallerActionHandler onMojoUpdate;

		public static void MojoUpdated(BBaller bballer)
		{
			if(onMojoUpdate != null)
				onMojoUpdate(bballer);
		}

		public static void DunkCompletedWithMojo(Team team)
		{
			if (onDunkCompletionWithMojo != null)
				onDunkCompletionWithMojo(team);
		}

		//!!! Probably no more use
		public static void DunkCompleted(Team team)
		{
			if (onDunkCompletion != null)
				onDunkCompletion(team);
		}

		public static void DemandDebugTextUpdate(bool debugMode)
		{
			if (onDemandDebugTextUpdate != null && debugMode)
				onDemandDebugTextUpdate();
		}

		public static void DemandCardStatRecalculation(Team team, bool hasPrimary)
		{
			if (onDemandCardStatRecalculation != null)
				onDemandCardStatRecalculation(team, hasPrimary);
		}

		public static void DerivedStatChanged(Team team)
		{
			if (onDerivedStatChange != null)
				onDerivedStatChange(team);
		}

		public static void PrimaryStatChanged(Team team)
		{
			if (onPrimaryStatChange != null)
				onPrimaryStatChange(team);
		}

		public static void BallPossessionUpdate()
		{
			if (onBallPossessionUpdate != null)
				onBallPossessionUpdate();
		}


	}
}